[PARAM]
CustName="餐飲系統工作站"
CorpName="葆光軟體"
CopyRight="FitSoft"
Calendar="YYYY/MM/DD"
DateSep="/"
IDMSG="IDMSG.MDB"
DBPWD=
IDMENUPort=1001
IDMENU=BK35MENU
DBProvider=SQL
DBSource=192.168.1.101
#DBSource=SERVER;NETWORK=dbmssocn
#DBProvider=JET
#DBSource=C:\BK35\EXE\BK35MENU.MDB
DefUserID=辦公室B

